Repository CAU23-Capstone-Design-2/BackEnd, pull requests merged in 2023-12, with the labels that each got.

#45 [ fetch ] /api/dev 구현
  .gitignore
  src/main/java/com/cau/vostom/config/SwaggerConfig.java
  src/main/java/com/cau/vostom/config/WebSecurityConfig.java
  src/main/java/com/cau/vostom/dev/controller/DevController.java
  src/main/java/com/cau/vostom/dev/service/DevKakaoAuthService.java
  src/main/resources/application-db.properties
Labels: dev

#46 [DEV] 사용자 학습 파일 업로드 기능 및 사용자 학습 상태 확인 기능 구현
  src/main/java/com/cau/vostom/user/controller/UserController.java
  src/main/java/com/cau/vostom/user/domain/User.java
  src/main/java/com/cau/vostom/user/service/UserService.java
  src/main/java/com/cau/vostom/util/api/ResponseCode.java
Labels: dev

#48 [FIX] 음악 요청 시 cache에 없는 경우는 cache 테이블에 저장
  src/main/java/com/cau/vostom/music/domain/Cache.java
  src/main/java/com/cau/vostom/music/service/MusicService.java
  src/main/java/com/cau/vostom/user/controller/UserController.java
Labels: fix

#51 [FIX/DEV] 기능 테스트 중 오류 수정
  src/main/java/com/cau/vostom/comment/controller/CommentController.java
  src/main/java/com/cau/vostom/comment/domain/Comment.java
  src/main/java/com/cau/vostom/comment/dto/request/CreateCommentDto.java
  src/main/java/com/cau/vostom/comment/service/CommentService.java
  src/main/java/com/cau/vostom/music/domain/MusicLikes.java
  src/main/java/com/cau/vostom/music/service/MusicService.java
  src/main/java/com/cau/vostom/team/controller/TeamController.java
  src/main/java/com/cau/vostom/team/dto/request/JoinTeamDto.java
  src/main/java/com/cau/vostom/team/service/TeamService.java
  src/main/java/com/cau/vostom/user/controller/UserController.java
  src/main/java/com/cau/vostom/user/domain/User.java
  src/main/java/com/cau/vostom/user/service/UserService.java
  src/main/java/com/cau/vostom/util/api/ResponseCode.java
  src/main/resources/application-db.properties
  src/main/resources/application.properties
Labels: bug, fix

#52 스트리밍 구현
  src/main/java/com/cau/vostom/music/controller/MusicController.java
  src/main/java/com/cau/vostom/music/service/MusicService.java
Labels: dev
